Repository nhamil/python-tilewe, pull requests merged in 2023-11, with the labels that each got.

#5 Use bigints instead of sets
  tilewe/__init__.py
Labels: enhancement

#6 Add example engines
  example_tournament.py
  tilewe/engine.py
Labels: enhancement

#7 Add method to efficiently get number of legal moves for a player
  tilewe/__init__.py
  tilewe/engine.py
Labels: enhancement

#8 Add move equality testing
  tilewe/__init__.py
Labels: enhancement

#10 Non-unique rotation support and small fixes
  test.py
  tilewe/__init__.py
Labels: bug, enhancement

#11 Enhance tournament structures and implement Elo
  tilewe/__init__.py
  tilewe/elo.py
  tilewe/tournament.py
Labels: enhancement

#12 add wallcrawler sample engine
  example_tournament.py
  tilewe/engine.py
Labels: enhancement

#13 add avg score to game results log
  tilewe/tournament.py
Labels: enhancement

#14 Null move support
  test.py
  tilewe/__init__.py
Labels: enhancement

#16 implement new elo outcome logic using win status instead of scores
  tilewe/elo.py
Labels: enhancement

#19 Add README
  README.md
  test.py
  tilewe/__init__.py
  tilewe/engine.py
Labels: documentation

#21 implement tournament results
  example_tournament.py
  tilewe/tournament.py
Labels: enhancement

#22 Fix crash on tournament game exception
  tilewe/tournament.py
Labels: bug

#24 Improve performance, fix wall crawler tile weight table bug
  tilewe/__init__.py
  tilewe/engine.py
Labels: bug, enhancement

#23 refactor WallCrawlerEngine to generic TileWeightEngine, fix bugs
  example_tournament.py
  tilewe/__init__.py
  tilewe/engine.py
Labels: enhancement

#25 fixes for multiprocessing issues on windows
  example_tournament.py
  tilewe/tournament.py
Labels: bug

#20 initial devops work, including requirements, style, and workflows
  .github/pre-commit.sample
  .github/workflows/python-app.yml
  LICENSE
  README.md
  example_tournament.py
  requirements-dev.txt
  requirements.txt
  scripts/validate_style.sh
  tilewe/__init__.py
  tilewe/elo.py
  tilewe/engine.py
  tilewe/pyproject.toml
  tilewe/setup.py
  tilewe/tests/test_elo.py
  tilewe/tests/test_moves.py
  tilewe/tournament.py
Labels: enhancement

#26 `add_corner` and `out_of_bounds` improvements
  tilewe/__init__.py
Labels: enhancement

#27 implement dataclasses
  tilewe/__init__.py
  tilewe/tournament.py
Labels: enhancement

#29 Speed overhaul
  tilewe/__init__.py
  tilewe/engine.py
  tilewe/tests/test_gameplay.py
Labels: enhancement

#30 refactor tournament wins/draws/losses, adjust displays
  tilewe/tournament.py
Labels: enhancement

#31 add `Board_NumPlayerPcs` C function for `board.n_remaining_pieces`
  tilewe/__init__.pyi
  tilewe/src/ctilewemodule.c
Labels: enhancement

#35 Re-add all remaining python functions to C extension
  tilewe/__init__.py
  tilewe/__init__.pyi
  tilewe/engine.py
  tilewe/src/ctilewemodule.c
  tilewe/tests/test_gameplay.py
  tilewe/tests/test_moves.py
  tilewe/tournament.py
Labels: bug, enhancement

#34 compute Elo error margins and display in tournament rankings
  requirements.txt
  tilewe/elo.py
  tilewe/engine.py
  tilewe/tournament.py
Labels: enhancement

#37 Add estimated Elo option
  example_tournament.py
  requirements.txt
  tilewe/elo.py
  tilewe/tournament.py
Labels: enhancement

#38 Convert most sample bots to support maximizing and minimizing their heuristic
  example_tournament.py
  pyproject.toml
  tilewe/__init__.py
  tilewe/engine.py
Labels: enhancement

#41 add simple search sample bot
  example_tournament.py
  tilewe/engine.py
Labels: enhancement
